### ISSUE TITLE
faceboxes的推理速度有吗？

### ISSUE THREAD

**Issue by wang-kangkang** [Star-Clouds/centerface#11]
faceboxes的推理速度有吗？

**Comment by ywlife** [comment]
麻烦查看lffd论文吧

**Comment by wang-kangkang** [comment]
好的，多谢。

我查到了，顺便放这儿吧，便于别人查看。
NVIDIA TX2 (MXNet+CUDA 9.0+CUDNN7.1)上速度对比：
resolution        160*120        320*240        640*480
FaceBoxes3.2x  11.20ms       19.62ms        72.74ms
LFFD                 7.30ms         19.64ms        64.70ms

**Comment by ywlife** [comment]
> 好的，多谢。
> 
> 我查到了，顺便放这儿吧，便于别人查看。
> NVIDIA TX2 (MXNet+CUDA 9.0+CUDNN7.1)上速度对比：
> resolution------160x120------320x240------640x480
> FaceBoxes3.2x--11.20ms-----19.62ms------72.74ms
> LFFD------------7.30ms-------19.64ms------64.70ms
> https://cloud.tencent.com/developer/article/1492082

faceboxes3.2是将input size放大3.2倍，实际项目没人会这么用。
