### ISSUE TITLE
why not tvm or onnxruntime

### ISSUE THREAD

**Issue by DCC-lzhy** [Star-Clouds/CenterFace#13]
仓库里的python代码是基于cv2.dnn的，我尝试着去用onnxruntime，但模型代码没有给，有些参数不知道设，如果作者有时间的话，可以放下tvm和onnxruntime的推理demo

**Comment by ywlife** [comment]
还未使用过onnxruntime和tvm，有时间的话再看看

**Comment by ywlife** [comment]
> 仓库里的python代码是基于cv2.dnn的，我尝试着去用onnxruntime，但模型代码没有给，有些参数不知道设，如果作者有时间的话，可以放下tvm和onnxruntime的推理demo

欢迎pr

**Comment by DCC-lzhy** [comment]
好的，我在尝试用tvm，onnxruntime是可以的，稍微改下就可以。我还有一个问题，你的输入是resize成32的倍数，然后我用Netron读取了onnx文件，发现输入的大小是10×3×32×32，这是如何做的？

**Comment by mhsszm** [comment]
@DCC-lzhy  输入的大小是10×3×32×32，可以改不定维度的吗，你们后面有解决吗？

**Comment by DCC-lzhy** [comment]
> @DCC-lzhy 输入的大小是10×3×32×32，可以改不定维度的吗，你们后面有解决吗？

他的demo里都是会把原大小resize成32的倍数，但是我不知道为什么模型图里的输入是10*3*32*32，这个模型是支持任意图片大小的，只要是32的倍数

**Comment by ywlife** [comment]
onnx模型是其他框架转换过来的，shape没有具体含义哦

**Comment by DCC-lzhy** [comment]
嗯，发现了，shape没有具体含义，只是个example

**Comment by hitzht** [comment]
使用onnxruntime解析模型，模型输入只能设置为10*3*32*32,如果改成32的倍数回报维度不匹配,请问有什么方式使得模型支持任意尺寸(32倍数)的输入?
例:输入维度为10*3*416*416出现以下错误
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: input.1 for the following indices
 index: 2 Got: 416 Expected: 32
 index: 3 Got: 416 Expected: 32

**Comment by CodingMice** [comment]
> @DCC-lzhy 输入的大小是10×3×32×32，可以改不定维度的吗，你们后面有解决吗？

OnnxRuntime貌似不可以改不定维度，TensorRT在windows上面没有pythonAPI..

**Comment by CodingMice** [comment]
> 还未使用过onnxruntime和tvm，有时间的话再看看

方便提供原训练模型的文件吗？这样我们可以根据需要去修改onnx输入的尺寸。目前使用cv2.dnn的推理框架只可以在cpu上运行，运行速度相对GPU比较慢。

**Comment by ywlife** [comment]
这个repo是用于学术讨论，现有的model已经够了。
