### ISSUE TITLE
ncnn版本

### ISSUE THREAD

**Issue by zhangyunming** [Star-Clouds/CenterFace#15]
hi，你好
      我将ncnn改了下做视频和摄像头的测试，但是跑一会后，cpu占用率会突然飙到96或以上，
是不是哪里没释放，泄漏了啊。

good job!

**Comment by ywlife** [comment]
Android平台?

**Comment by zhangyunming** [comment]
不是啊， 就是在pc cpu下跑了下。还没有移植到安卓。

**Comment by ywlife** [comment]
边缘设备用的挺好的，没发现错误呢
