### ISSUE TITLE
您好，方便上传下CenterFace-small的模型文件吗？

### ISSUE THREAD

**Issue by zjd1988** [Star-Clouds/CenterFace#16]
转换成阿里MNN模型，在树梅派4b上，4线程，输入3x480x640，推理消耗大概340ms+，不知道small模型有多大提升呢？

**Comment by ywlife** [comment]
- smal model因为商用了，不方便发布。
- 以后会在其他仓库发布一个速度快一点的，android平台大概10ms左右吧。

**Comment by zjd1988** [comment]
@ywlife  好的，谢谢啦！

**Comment by lucwan** [comment]
is the CenterFace-small model available online?
