### ISSUE TITLE
检测过摆头角度大的人脸后，landmark出现错误

### ISSUE THREAD

**Issue by hipitt** [Star-Clouds/CenterFace#18]
cv dnn版有个奇怪的现象，当检测过摆头角度很大的人脸后，再检测其他人脸照片时 landmark混乱，甚至跑到人脸范围以外，请问什么原因？prj-opencv-cpp/用的onnx模型

**Comment by ywlife** [comment]
是prj-python，还是prj-opencv-cpp工程？

**Comment by hipitt** [comment]
是prj-opencv-cpp

**Comment by hipitt** [comment]
是prj-opencv-cpp @ywlife

**Comment by ywlife** [comment]
方便相关的image上传一下吗

**Comment by ywlife** [comment]
加入qq群里把吧讨论吧。
