### ISSUE TITLE
测试速度-420ms/张

### ISSUE THREAD

**Issue by zhanglaplace** [Star-Clouds/centerface#2]
您好，我在macos上，从摄像头读取图片测试，时间大约是420ms。这个速度正常吗。
![image](https://user-images.githubusercontent.com/12178974/66937211-a31bf580-f071-11e9-9d53-cd45144240d2.png)

**Comment by ywlife** [comment]
不正常，图像的宽高分别是多少？

**Comment by zhanglaplace** [comment]
@ywlife 摄像头默认读取的是720*1280的。后续测试输入了512X288的图片测试时间是 100ms。 
640*480的时间是 200ms ,这个时间正常吗～

**Comment by jiagh2010** [comment]
There are two questions: first, I also calculate the average time of different resolution pictures is more than 100 milliseconds; second, how to use GPU acceleration? @ywlife

**Comment by ywlife** [comment]
1. May be difference from test computer.
2. You can use caffe2 or other frameworks to load the onnx, and then run on GPU.

**Comment by jiagh2010** [comment]
Other frameworks can also call the onnx model？？？@ywlife

**Comment by zhanglaplace** [comment]
> Other frameworks can also call the onnx model？？？@ywlife

@jiagh2010 Onnx to caffe2 . https://github.com/qfgaohao/pytorch-ssd/blob/master/convert_to_caffe2_models.py

**Comment by jiagh2010** [comment]
@jiagh2010 Onnx to caffe2 . https://github.com/qfgaohao/pytorch-ssd/blob/master/convert_to_caffe2_models.py    I will convert the model to the Pb format of caffe2, but I will not call it. Can you give me an example?@ywlife @zhanglaplace

**Comment by zhanglaplace** [comment]
> @jiagh2010 Onnx to caffe2 . https://github.com/qfgaohao/pytorch-ssd/blob/master/convert_to_caffe2_models.py I will convert the model to the Pb format of caffe2, but I will not call it. Can you give me an example?@ywlife @zhanglaplace
try it :
https://github.com/qfgaohao/pytorch-ssd/blob/master/convert_to_caffe2_models.py .

**Comment by lufi1** [comment]
Hi, 

Im facing the same issue. Any idea about how I could deal with it ? 
I m on macos and trying to reproduce your results
