### ISSUE TITLE
face image quality

### ISSUE THREAD

**Issue by peyer** [Star-Clouds/CenterFace#21]
@ywlife Your released paper mentioned that RetainFace introduced five levels of face image quality and annotates five landmarks on faces.
I only found 5 landmarks ground-truth from RetainFace(InsightFace github resposity), but did not find quality ground-truth. 
How could I got it?

**Comment by ywlife** [comment]
Related annotations can be found from retinaface's papers, but I only found 5 points of annotations. And maybe asking better from retinaface repo.
