### ISSUE TITLE
training code will release ?

### ISSUE THREAD

**Issue by lexuszhi1990** [Star-Clouds/CenterFace#22]

**Comment by ywlife** [comment]
There are no plans to release training code at this time.

**Comment by lexuszhi1990** [comment]
that's ok. I am just curious about that CenterFace is so similar with CenterNet 😄

**Comment by leeyunhome** [comment]
> There are no plans to release training code at this time.

Hello,

Thanks for the good material.

Do you currently provide code to train the CenterFace algorithm using a custom dataset?

Thank you.
