### ISSUE TITLE
Need Training Code and DataSet

### ISSUE THREAD

**Issue by amitsrivastava78** [Star-Clouds/CenterFace#23]
Hi ,
      Your paper looks exiting but there is no training and data-set available, can you please provide the same so that we can evaluate the paper independently.

Regards
Amit

**Comment by ywlife** [comment]
Thank you for your attention. But there is no plan to release training code at present.

**Comment by abhigoku10** [comment]
@ywlife  when can we expect the training pipeline to be released??
