### ISSUE TITLE
Occluded landmark

### ISSUE THREAD

**Issue by bhack** [Star-Clouds/CenterFace#25]
How are you handling the loss for occluded landmarks?
I was looking for this detail in the paper but I didn't find anything.

**Comment by tfygg** [comment]
> How are you handling the loss for occluded landmarks?
> I was looking for this detail in the paper but I didn't find anything.


According to the face annotation of widerface, we filter the occluded face in the landmark task.

**Comment by bhack** [comment]
> > How are you handling the loss for occluded landmarks?
> > I was looking for this detail in the paper but I didn't find anything.
> 
> According to the face annotation of widerface, we filter the occluded face in the landmark task.

I meant more the case when you have one or two occluded landmarks so a very partial occlusion of the face.

**Comment by tfygg** [comment]
> I meant more the case when you have one or two occluded landmarks so a very partial occlusion of the face.

This case doesn't matter, and it can be used for training.

**Comment by bhack** [comment]
So here:
> Different from Box regression, the regression of the five facial landmarks adopts the target normalization method 
based on the center position.

So if you have on a face just 4 visibile landmarks are you simply going to exclude that one from the regression?

**Comment by tfygg** [comment]
> So here:
> 
> > Different from Box regression, the regression of the five facial landmarks adopts the target normalization method
> > based on the center position.
> 
> So if you have on a face just 4 visibile landmarks are you simply going to exclude that one from the regression?


Invisible points still regression. And this can improve the robustness of landmarks detection.

**Comment by bhack** [comment]
This Is valid only if you have occluded points in GT.
