### ISSUE TITLE
WiderFace results

### ISSUE THREAD

**Issue by hegc** [Star-Clouds/CenterFace#26]
Hi, you get the better results than retinaface on WiderFace-Val, you input the image of the WiderFace-val in origin size? We know that the performace will be bettter when the size of input is larger.

**Comment by tfygg** [comment]
The performance results in Table 4 of the paper use a multi-scale strategy, And for SIO(Single Inference on the Original) evaluation schema, CenterFace produces 92.2% (Easy), 91.1% (Medium) and 78.2% (Hard) for validation set.

**Comment by tfygg** [comment]
> Hi, you get the better results than retinaface on WiderFace-Val, you input the image of the WiderFace-val in origin size? We know that the performace will be bettter when the size of input is larger.

The performance results in Table 4 of the paper use a multi-scale strategy, and for SIO(Single Inference on the Original) evaluation schema, CenterFace produces 92.2% (Easy), 91.1% (Medium) and 78.2% (Hard) for validation set.

**Comment by ywlife** [comment]
The performance results in Table 4 of the paper use a multi-scale strategy, and for SIO(Single Inference on the Original) evaluation schema, CenterFace produces 92.2% (Easy), 91.1% (Medium) and 78.2% (Hard) for validation set.
