### ISSUE TITLE
Threshold

### ISSUE THREAD

**Issue by doublex** [Star-Clouds/CenterFace#30]
Your demos are very impressive.
What `scoreThresh` and `nmsThresh` did you set to create these? 
The default ones?

**Comment by ywlife** [comment]
> Your demos are very impressive.
> What `scoreThresh` and `nmsThresh` did you set to create these?
> The default ones?

Default parameters?

**Comment by Edwardmark** [comment]
Your demos are very impressive.
What scoreThresh and nmsThresh did you set to create these?
The default ones?

**Comment by ywlife** [comment]
I don't really understand your problem.

**Comment by Edwardmark** [comment]
@ywlife when you draw the face boxes detected by the model, you should set a face classification threshold, i.e. 0.5, so you can draw the box with prob greater than 0.5, so what is your threshold?

**Comment by Edwardmark** [comment]
@ywlife and could you please anser this question? Thanks. 
https://github.com/Star-Clouds/CenterFace/issues/35

**Comment by ywlife** [comment]
The threshold of score is 0.5.
