### ISSUE TITLE
which layer you use to attach detection head?

### ISSUE THREAD

**Issue by jiashu-zhu** [Star-Clouds/CenterFace#32]
首先感谢你们贡献如此出色的idea！但是我在阅读论文过程中碰到了一些问题
在论文3.1部分，你们在P3，P4，P5层后加上了FPN，这三个层对应于原图分别下采样8、16、32倍，但是在论文3.2中，又说取下采样4倍的layer加检测头，这让我十分疑惑，是否论文有些错误？
期待您的回复

**Comment by ujsyehao** [comment]
@jiashu-zhu 论文中就是写错了
