### ISSUE TITLE
why add 0.5 in decode the x1, y1? 

### ISSUE THREAD

**Issue by lishiyuwhu** [Star-Clouds/CenterFace#38]
in decode() part, 

1. 
https://github.com/Star-Clouds/CenterFace/blob/master/prj-python/centerface.py#L63

```x1, y1 = max(0, (c1[i] + o1 + 0.5) * 4 - s1 / 2), max(0, (c0[i] + o0 + 0.5) * 4 - s0 / 2)```

what's the 0.6 means? why not  ```(center_point_x + offset_x)*scale  -  width/2 ```? 

2. 
```s0, s1 = np.exp(scale0[c0[i], c1[i]]) * 4, np.exp(scale1[c0[i], c1[i]]) * 4```
it means
```scale0[c0[i], c1[i]]  =  bbox_width/ img_width_before_resize``` ?

**Comment by ywlife** [comment]
Related to the definition  of ground turth offset.
