### ISSUE TITLE
Test prj-ncnn in ubuntu

### ISSUE THREAD

**Issue by weilanShi** [Star-Clouds/CenterFace#40]
when i install the ncnn and test prj-ncnn in ubuntu cmake && make it , i encountered the following problems: 
fatal error: net.h: No such file or directory
compilation terminated.
CMakeFiles/demo.dir/build.make:62: recipe for target 'CMakeFiles/demo.dir/cpp/ncnn_centerface.cpp.o' failed
who can tell me why this error occured, thanks

**Comment by ywlife** [comment]
Maybe you should check environment of ncnn.

**Comment by immarioo** [comment]
hello，i met the same problem, do you know how to solve this?
