### ISSUE TITLE
在测试时cmake && make 报错

### ISSUE THREAD

**Issue by weilanShi** [Star-Clouds/CenterFace#43]
作者你好，我在ubuntu 16.04下测试prj-ncnn时 make 报错，ncnn已经安装编译成功，cmake 时顺利通过，我的环境如下：ubuntu 16.04 ,  python3.6,  opencv 4.1,  cmake3.9.1， gcc5.4 ，protobuf2.6.1,请问这个项目对环境有具体要求吗？

**Comment by ywlife** [comment]
没有特殊的要求，建议使用最新的ncnn，再编译试试
