### ISSUE TITLE
Bad Accuracy..Real world accuracy is half

### ISSUE THREAD

**Issue by dexception** [Star-Clouds/CenterFace#44]
I have tested this model on my own 5000 images and the accuracy seems to be half of the claimed.

5 faces detected in the following is a disaster.
https://ibb.co/PCL0qNv

**Comment by ywlife** [comment]
The image is too big.

**Comment by uday60** [comment]
@ywlife 
Tested with small images also. There seems to be accuracy issues in the model. 
I am also getting similar results. Tested with 1000 images. The accuracy is only 54%.
Missed plenty of faces in newspapers images, small faces, false positive is large images. 
Also cannot run your model on live camera as it is too slow.

**Comment by uday60** [comment]
@ywlife 
This is not a big image. Can your share your feedback why landmarks are inaccurate ?

![temp](https://user-images.githubusercontent.com/39152652/73665165-aa214f00-46c6-11ea-8fc9-1243c8879e0c.jpg)

**Comment by pytyeah** [comment]
> @ywlife
> Tested with small images also. There seems to be accuracy issues in the model.
> I am also getting similar results. Tested with 1000 images. The accuracy is only 54%.
> Missed plenty of faces in newspapers images, small faces, false positive is large images.
> Also cannot run your model on live camera as it is too slow.

Hi~ I meet the same problem, have you solved it ?

**Comment by ldthinh** [comment]
padding your image to 800x800 like paper was released, it will work fine
