### ISSUE TITLE
Image Quality Issue

### ISSUE THREAD

**Issue by PhenomenalOnee** [Star-Clouds/CenterFace#45]
Great Work..
But can you tell  how to handle image quality issue
The model is detecting blur faces too and providing poor result
i want to eliminate blur faces
the score of blur face detected is high too

**Comment by ywlife** [comment]
> Great Work..
> But can you tell how to handle image quality issue
> The model is detecting blur faces too and providing poor result
> i want to eliminate blur faces
> the score of blur face detected is high too

The problems of face blur and face detection are different and you can refer to relevant face quality papers.
