### ISSUE TITLE
Failed to execute prj-opencv-cpp

### ISSUE THREAD

**Issue by ruoyuryc** [Star-Clouds/CenterFace#47]
When excute  **./demo ../../models/onnx your_image_path** 
will return 
**terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.1.1) ../modules/dnn/src/onnx/onnx_importer.cpp:57: error: (-210:Unsupported format or combination of formats) Failed to parse onnx model in function 'ONNXImporter'**
Do you know how to solve it?
Thanks!

**Comment by ywlife** [comment]
Sorry, I do not kown the reason.

**Comment by chaotianjiao** [comment]
@ruoyuryc you should run like this ./demo ../../models/onnx/centerface.onnx  your_image_path
