### ISSUE TITLE
The key points are not calculated as described in the paper？

### ISSUE THREAD

**Issue by chenjun2hao** [Star-Clouds/CenterFace#49]
why the key points are not calculated as described in the paper?
>> the regression of the five facial landmarks adopts the target normalization method based on the center position
however the code is based on the left-top point.
>> facebox.landmarks[2*j] = x1 + lm[(2*j+1)*spacial_size+index] * s1

**Comment by tim20120526** [comment]
i have the same confusion.

**Comment by linkyeh** [comment]
i have the same confusion.

**Comment by deep-practice** [comment]
The landmarks are not as good as retinaface.

**Comment by ywlife** [comment]
Yes, the release code of landmark is different from the origin paper.
