### ISSUE TITLE
Thresholds for widerface evaluation

### ISSUE THREAD

**Issue by ufoym** [Star-Clouds/CenterFace#51]
Thanks for your excellent work! For SIO(Single Inference on the Original) evaluation schema, I get bad results on widerface validation set. Maybe it is due to the suboptimal thresholds (thres_score, thres_nms, etc). Could you please share your thresholds for widerface evaluation? Thanks pretty much!

**Comment by ywlife** [comment]
> Thanks for your excellent work! For SIO(Single Inference on the Original) evaluation schema, I get bad results on widerface validation set. Maybe it is due to the suboptimal thresholds (thres_score, thres_nms, etc). Could you please share your thresholds for widerface evaluation? Thanks pretty much!

You can refer to the python code.

**Comment by ufoym** [comment]
https://github.com/Star-Clouds/CenterFace/blob/ef5afcda9635003bc71be71c3b4e13a349c382c7/prj-python/demo.py#L77
The above thresholds were used for widerface evaluation, but only get some poor results (Easy 0.02, Medium 0.03, Hard 0.03). But if I set thres_score=0.5, then the result seems much better (Easy 0.49, Medium 0.55, Hard 0.36). That is why I think there should be something wrong with my experiments.
