### ISSUE TITLE
the train dataset

### ISSUE THREAD

**Issue by chenjun2hao** [Star-Clouds/CenterFace#52]
I'm trying to reproduce the results of the paper, and this is what I have now. Is this your [training data set](https://github.com/deepinsight/insightface/tree/master/RetinaFace)?
```
Easy   Val AP: 0.9230461666813543
Medium Val AP: 0.9050905330904577
Hard   Val AP: 0.679394673204941
```
thanks.

**Comment by ywlife** [comment]
Yes.
