### ISSUE TITLE
the train image size

### ISSUE THREAD

**Issue by chenjun2hao** [Star-Clouds/CenterFace#53]
I'm trying to reproduce the results of the paper, and this is result I have now. 
```
Easy   Val AP: 0.9136305801084846
Medium Val AP: 0.9004443217585435
Hard   Val AP: 0.7486346101347016
```
i test the val dataset with 800*800，but can not reach the accuracy in papers.Do you follow the training details in the paper。
thanks.

**Comment by ywlife** [comment]
Yes.

**Comment by Sarthak-005** [comment]
@chenjun2hao @ywlife  Can you pls tell me the input size of images for validation and test set being fed into the model and also the threshold used to obtain the results you got in the paper?
I tried  it on 1280*720 with thresh=0.1 and got the following results:
Easy Val AP : 0.803
Medium Val AP : 0.826
Hard Val AP :  0.728
