### ISSUE TITLE
the train tricks

### ISSUE THREAD

**Issue by chenjun2hao** [Star-Clouds/CenterFace#54]
你好，我尝试复现你关于人脸检测centerface的论文。现在的测试精度为：

Easy   Val AP: 0.9136305801084846
Medium Val AP: 0.9004443217585435
Hard   Val AP: 0.7486346101347016

我用python的测试代码跑过之后，您的精度大概为

Easy   Val AP: 0.9374034028106627
Medium Val AP: 0.9309832270920672
Hard   Val AP: 0.8438475609433239

同时我将测试的图片固定为800×800的时候，并不能达到这个精度。论文中说是用800×800训练的。但是用800×800进行测试效果还相对低一些。

请问，您是采用了什么训练策略吗？感谢。

**Comment by ywlife** [comment]
Hi，chenjun


&nbsp; &nbsp; &nbsp;测试不需要resize到800*800。数据增强就是paper里面的那样。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chenjun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月18日(星期二) 晚上9:00
收件人:&nbsp;"Star-Clouds/CenterFace"<CenterFace@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Star-Clouds/CenterFace] the train tricks (#54)




你好，我尝试复现你关于人脸检测centerface的论文。现在的测试精度为：
 
Easy   Val AP: 0.9136305801084846
 Medium Val AP: 0.9004443217585435
 Hard   Val AP: 0.7486346101347016
 
我用python的测试代码跑过之后，您的精度大概为
 
Easy   Val AP: 0.9374034028106627
 Medium Val AP: 0.9309832270920672
 Hard   Val AP: 0.8438475609433239
 
同时我将测试的图片固定为800×800的时候，并不能达到这个精度。论文中说是用800×800训练的。但是用800×800进行测试效果还相对低一些。
 
请问，您是采用了什么训练策略吗？感谢。
