### ISSUE TITLE
ONNX model benchmarks on widerface hard dont match those listed in the paper

### ISSUE THREAD

**Issue by kushalchordiya216** [Star-Clouds/CenterFace#55]
I'm using the onnx model in your repository (in models/onnx/centerface.onnx) to test benchmarks on the wider face val set. The AP results on easy medium and hard are as follows

Easy   Val AP: 0.922375391848484
Medium Val AP: 0.9111946804934881
Hard   Val AP: 0.7821960485483465

These dont match with the benchmarks listed in the paper published on arxiv [https://arxiv.org/abs/1911.03599](url), especially for the hard dataset, which is reported to have mAP of 87.5 in the paper. 

Is there some kind of preprocessing that has to be done to the images, like a image pyramid for it the give reported AP metrics?

**Comment by ywlife** [comment]
> I'm using the onnx model in your repository (in models/onnx/centerface.onnx) to test benchmarks on the wider face val set. The AP results on easy medium and hard are as follows
> 
> Easy Val AP: 0.922375391848484
> Medium Val AP: 0.9111946804934881
> Hard Val AP: 0.7821960485483465
> 
> These dont match with the benchmarks listed in the paper published on arxiv [https://arxiv.org/abs/1911.03599](url), especially for the hard dataset, which is reported to have mAP of 87.5 in the paper.
> 
> Is there some kind of preprocessing that has to be done to the images, like a image pyramid for it the give reported AP metrics?

For SIO(Single Inference on the Original) evaluation schema, CenterFace also produces 92.2% (Easy), 91.1% (Medium) and 78.2% (Hard) for validation set. The benchmarks listed in the paper are under mutil scales schema.
