### ISSUE TITLE
About whether use BatchNorm in network head

### ISSUE THREAD

**Issue by ujsyehao** [Star-Clouds/CenterFace#59]
Hi, in your published ncnn model, its network head below:
![02-2](https://user-images.githubusercontent.com/17454232/75663890-8e509f00-5cac-11ea-9cef-8290af685f95.png)
**it doesn't use Batchnorm after 3x3 conv.**

but in onnx model, its network head below:
![02-3](https://user-images.githubusercontent.com/17454232/75663931-a3c5c900-5cac-11ea-826e-230c1637364b.png)
**it uses Batchnorm after 3x3 conv.**

So whether to use BN after 3x3 conv?

**Comment by ywlife** [comment]
It may be that ncnn has optimized and merged Batchnorm.

**Comment by ujsyehao** [comment]
Oh Oh
