### ISSUE TITLE
FDDB结果很差？

### ISSUE THREAD

**Issue by sharepointer** [Star-Clouds/CenterFace#60]
mnn模型在FDDB上表现很差，测试方法有问题？
可以分享一下你的评测结果吗？

**Comment by ywlife** [comment]
你测试结果是多少呢？Python的版本测试了么？

**Comment by sharepointer** [comment]
用提供的mnn工程和mnn模型，现象是人脸的score普遍比较低
FDDB结果：50@0.43  100@0.65  237@0.95
 似乎低误检的要求下，召回率不高

**Comment by sharepointer** [comment]
HI，ywlife
测了下python版本，结果不错^_^。FDDB结果：50@0.885  100@0.918  200@0.950
多谢分享！

另外，onnx转的mnn么？mnn模型差异比较大哈~
