### ISSUE TITLE
About MAP

### ISSUE THREAD

**Issue by oyrq** [Star-Clouds/CenterFace#67]
Hi，
I make a test on WIDERFACE val dataset，the input size of centerface network is 1920x1088(width x height), So the map result is:

Easy   Val AP: 0.8841115597905682
Medium Val AP: 0.8755813460085787
Hard   Val AP: 0.7423266548239988

Please, What is the network input size of the author ? and how to test for the same results as the author ?

Thanks.

**Comment by ywlife** [comment]
You can refer to this code, 
https://github.com/Star-Clouds/CenterFace/blob/c932596bcb6015acf73fb7eb26f95d40acb11666/prj-python/demo.py#L70

**Comment by oyrq** [comment]
> You can refer to this code,
> https://github.com/Star-Clouds/CenterFace/blob/c932596bcb6015acf73fb7eb26f95d40acb11666/prj-python/demo.py#L70

I got it, Thanks!

**Comment by Sarthak-005** [comment]
@oyrq can you pls help me calculate mAP?
