### ISSUE TITLE
the tensorrt version and devices

### ISSUE THREAD

**Issue by Samonsix** [Star-Clouds/CenterFace#69]
I can't run tensorrt demo, 
python: engine.cpp:1104: bool nvinfer1::rt::Engine::deserialize(const void*, std::size_t, nvinfer1::IGpuAllocator&, nvinfer1::IPluginFactory*): Assertion `size >= bsize && "Mismatch between allocated memory size and expected size of serialized engine."' failed.

would you tell me the tensorrt version and devices?

**Comment by ywlife** [comment]
Tensorrt7.

**Comment by iytChen** [comment]
same question, do u fix it?@\ @Samonsix
