### ISSUE TITLE
Error when using different image sizes after loading model!

### ISSUE THREAD

**Issue by KhanhDinhDuy** [Star-Clouds/CenterFace#74]
Hello, I am facing an issue of getting wrong result when using your demo.py file in this folder "prj-python". Firstly, I load the model. After that, I check the results with different image sizes in a folder. The first image is ok, but then I only get very bad results with other images that have different sizes with the first one.
Please help me with this problem.
Thank you

**Comment by ywlife** [comment]
If image sizes is different, we must load the model with the different sizes. 
Or you can refactor code of preprocess.

**Comment by KhanhDinhDuy** [comment]
Thanks you!!!!

**Comment by xuguozhi** [comment]
before inference, add resize will be ok
