### ISSUE TITLE
mnn例子， 用cpu正常，用gpu报错

### ISSUE THREAD

**Issue by duoduo1018** [Star-Clouds/CenterFace#77]
用gpu会报错：
start detect.
Don't support too large feature: 960 x 528
Resize error for [Convolution], 363, code=2
Can't run session because not resized
end detect.

报错地址为：	centerface_interpreter_->resizeSession(centerface_sess_);

测试图片为：1920*1080大小，求大神指导，非常感谢

**Comment by ywlife** [comment]
输入图像的宽高必须是32的整数倍。
