### ISSUE TITLE
您好，请问怎么将C++的代码使用GPU运行？

### ISSUE THREAD

**Issue by njustymk** [Star-Clouds/CenterFace#81]
我在windows上安装了ncnn并将代码跑了起来，但是每张图像测试需要400ms左右的时间，想问下如何将代码使用GPU跑？我的卡是RTX2080TI，谢谢。

**Comment by alicera** [comment]
请问你有在手机上跑过吗

**Comment by njustymk** [comment]
> 请问你有在手机上跑过吗

抱歉，没有。

**Comment by ywlife** [comment]
使用mnn在手机上跑会快一点，int8后会更快。
