### ISSUE TITLE
The Tensorrt inference does not release memory after execution

### ISSUE THREAD

**Issue by xxxpsyduck** [Star-Clouds/CenterFace#86]
When using tensorrt model for video, it keeps eating more and more GPU memory until causing OOM. 
```sh
[TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
[TensorRT] ERROR: FAILED_ALLOCATION: std::exception
```

**Comment by xxxpsyduck** [comment]
I use the following code for demo of tensorrt
```python
def camera():
    cap = cv2.VideoCapture(0)
    ret, frame = cap.read()
    h, w = 960, 1280
    centerface = CenterFace()

    while True:
        ret, frame = cap.read()
        dets, lms = centerface(frame, h, w, threshold=0.35)
        for det in dets:
            boxes, score = det[:4], det[4]
            cv2.rectangle(frame, (int(boxes[0]), int(boxes[1])), (int(boxes[2]), int(boxes[3])), (2, 255, 0), 1)
        # if landmarks:
        for lm in lms:
            for i in range(0, 5):
                cv2.circle(frame, (int(lm[i * 2]), int(lm[i * 2 + 1])), 2, (0, 0, 255), -1)
        cv2.imshow('out', frame)
        # Press Q on keyboard to stop recording
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    cap.release()
if __name__ == '__main__':
    camera()
```

**Comment by xxxpsyduck** [comment]
@ywlife Can you give me some help?

**Comment by xxxpsyduck** [comment]
Solved

**Comment by jiagh2010** [comment]
how to solve？？@xxxpsyduck   [TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)

**Comment by xxxpsyduck** [comment]
take the memory allocation to the init function so that it only happens once

**Comment by jiagh2010** [comment]
this my code：


def test_image_tensorrt():

    centerface = CenterFace()
    input="../data/"
    i=0
    s=0
    for root, dirs, files in os.walk(input):
        for file in files:
            if os.path.splitext(file)[1] == '.jpg':
               print(os.path.join(root, file))

               imgpath=os.path.join(root, file)
               frame = cv2.imread(imgpath)
               #frame = cv2.resize(frame, (1088,1920))
               h, w = 480, 640  # must be 480* 640
               #centerface = CenterFace()
               t1=time.time()
               dets, lms = centerface(frame, h, w, threshold=0.35)
               t2=time.time()
               print("facenum: ", len(dets))


@xxxpsyduck

**Comment by xxxpsyduck** [comment]
@jiagh2010 you need to make changes in centerface.py

**Comment by zhangdengp** [comment]
i have the same problem, can you show detailed? @xxxpsyduck  
thank you

**Comment by xxxpsyduck** [comment]
@zhangdengp in current centerface.py, the function allocate_buffers() is called everytime you call inference_tensorrt(). You need to move it to the __init__() so it only gets called once.

**Comment by zhangdengp** [comment]
solved it,thanks very much @xxxpsyduck

**Comment by jiagh2010** [comment]
@zhangdengp zhangdengp   Can you share the code?

**Comment by pytyeah** [comment]
@zhangdengp  Hi~ I meet the same problem, can you tell me how to solve it,please?
